include: package:very_good_analysis/analysis_options.3.1.0.yaml

analyzer: 
  errors: 
    argument_type_not_assignable: ignore
    inference_failure_on_untyped_parameter: ignore
    unnecessary_lambdas: ignore

linter:
  rules:
    public_member_api_docs: false
    always_use_package_imports: false
    sort_unnamed_constructors_first: true
    sort_constructors_first: false
    avoid_dynamic_calls: false
